server:
  port: 8021

spring:
  application:
    name: API-Gateway
  cloud:
    discovery:
      enabled: true
    gateway:
      routes:
        - id: SignUp-Form
          uri: http://localhost:5009/
          predicates:
            - Path=/api/**
        - id: LOGIN
          uri: http://localhost:5008/
          predicates:
            - Path=/ap/**
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/